- hosts: all
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install dependencies
      apt:
        name:
        - wget
        - screen
        - unzip
        - openjdk-21-jdk
        state: latest